import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { SpeedInsights } from "@vercel/speed-insights/next";
import TopNav from "./_components/topnav";

export const metadata: Metadata = {
  title: "S3 Drive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <SpeedInsights />
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="relative z-0">
          <div className="grid h-full grid-rows-[auto,1fr]">
            <main className="">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
